package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"

	"github.com/Tabed23/Fun-Application-Projects/tree/main/JobsAPI-GraphQL/database"
	"github.com/Tabed23/Fun-Application-Projects/tree/main/JobsAPI-GraphQL/graph/model"
)

// CreateJob is the resolver for the CreateJob field.
func (r *mutationResolver) CreateJob(ctx context.Context, input model.CreateJobInput) (*model.CreateJobResponse, error) {
	return db.CreateJob(ctx, input)
}

// UpdateJob is the resolver for the UpdateJob field.
func (r *mutationResolver) UpdateJob(ctx context.Context, id string, input model.UpdateJobInput) (*model.UpdateJobResponse, error) {
	return db.UpdateJob(ctx, id, input)
}

// DeleteJob is the resolver for the DeleteJob field.
func (r *mutationResolver) DeleteJob(ctx context.Context, id string) (*model.DeleteJobResponse, error) {
	return db.DeleteJob(ctx, id)
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context) ([]*model.JobList, error) {
	return db.GetJobs(ctx)
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, id string) (*model.JobList, error) {
	return db.GetJobByID(ctx, id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var db = database.Connect()
